const DATABASE_NAME = '@timos';

const USER_COLLECTION = `${DATABASE_NAME}:user`;
const TOKEN_COLLECTION = `${DATABASE_NAME}:token`;
const REFRESH_TOKEN_COLLECTION = `${DATABASE_NAME}:refreshToken`;

export {
  USER_COLLECTION,
  TOKEN_COLLECTION,
  REFRESH_TOKEN_COLLECTION
};